# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'TestDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for TestDemo

pod 'ReactiveObjC', '~> 2.1.2'
#谷歌所用的接入SKD
#pod 'Google/SignIn'  舍弃
pod 'GTMAppAuth'
pod 'GoogleAPIClientForREST/Calendar'
#pod 'UICKeyChainStore', '~> 2.1.1'

#Office365所用的接入SKD
#pod 'ADAL', '~> 2.4.1' 舍弃
pod 'MSGraphSDK'
pod 'MSGraphSDK-NXOAuth2Adapter'
end
